linters-settings:
  deadcode:
    skip-files: "_test\\.go$"
  govet:
    check-shadowing: false
  golint:
    exclude-use-default-exported: true
    exclude-useless-naming: true
  gosec:
    tests: true
  unused:
    check-exported: true
    check-blank: true
    check-tests: true
