name: Taskfile CI

on:
  push:
    branches:
      - main
      - task-ci
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v17

      - name: Install Task
        uses: nicknovitski/nix-develop@v1
        with:
          arguments: "bsf/.#devShell"

      - name: go test
        run: task test
